# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reports',
            options={},
        ),
        migrations.AddField(
            model_name='reports',
            name='speaking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
