# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-11 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_auto_20180307_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='speaking_date',
        ),
    ]
