# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-11 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_remove_reports_speaking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
